### ISSUE TITLE
Gradle Code

### ISSUE THREAD

**Issue by tellfa** [yankai-victor/RingButton#1]
hi , please insert build.gradle code
for example :     compile 'com.android.support:design:22.2.0'

**Comment by yankai-victor** [comment]
Sorry,I don't get your point.
Do you mean this [build.gradle](https://github.com/yankai-victor/RingButton/blob/master/example/build.gradle)?

**Comment by tellfa** [comment]
yeah, my mean in build.gradle

**Comment by yankai-victor** [comment]
I update the build.gradle to the latest version.
I clone this project. And import it into Android Studio. It works fine.

**Comment by yankai-victor** [comment]
@tellfa 
Sorry，I just get your point.
I upload it to jcenter. So now you can use this code to add the library.

```
compile 'com.victor.ringbutton:lib:1.0'
```
