### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MansoorJafari** [yankai-victor/RingButton#4]
Hi
How to change Typeface this RingButton?
Thank you.

**Comment by yankai-victor** [comment]
I'm sorry. It can't change the typeface.
But I think you can add this feature by youself. It isn't very difficult.
Also I'll help you, if you have any question. :)

**Comment by MansoorJafari** [comment]
Thank you!
I don't have library for change fonts.

**Comment by MansoorJafari** [comment]
Thank you for your guide.
I could do this.
